# https://docs.spring.io/spring-boot/docs/3.1.x/reference/htmlsingle/#web.security.oauth2.authorization-server
spring:
  security:
    user:
      # bcrypt of password
      password: '{bcrypt}$2a$14$wAytVtOdFf3zexfmwugM7u0HmyN/L2YCcTeQ651SjuhW8Qy2ajMgG'
  sql:
    init:
      schema-locations: 'classpath:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql'
server:
  port: 9090